---
# tasks file for lvm-ansible-role

- name: Remove logical volume
  lvol:
    vg: "{{ item.vg_name }}"
    lv: "{{ item.lv_name }}"
    state: absent
    force: yes
  loop: "{{ lvm_volumes }}"
  when: >
    item.state is defined and item.state == "absent"

- name: Remove volume group
  lvg:
    vg: "{{ item.vg_name }}"
    pvs: /dev/{{ item.disk }}{% if item.create_partition is defined and item.create_partition %}1{% endif %}
    state: absent
  loop: "{{ lvm_volumes }}"
  when: >
    item.state is defined and item.state == "absent"

- name: Remove GPT partition
  command: "parted /dev/{{ item.disk }} rm 1"
  loop: "{{ lvm_volumes }}"
  when: >
    item.disk + "1" in lsblk_list.stdout and
    (item.state is defined and item.state == "absent") and
    (item.create_partition is defined and item.create_partition)
